services:
  postgres:
    image: ${POSTGRES_IMAGE}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5
  nakama:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${NAKAMA_IMAGE}
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB} &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB} --socket.server_key ${NAKAMA_SOCKET_SERVER_KEY} --runtime.http_key ${NAKAMA_RUNTIME_HTTP_KEY} --session.encryption_key ${NAKAMA_SESSION_ENCRYPTION_KEY} --session.refresh_encryption_key ${NAKAMA_SESSION_REFRESH_ENCRYPTION_KEY} --console.password ${NAKAMA_CONSOLE_PASSWORD} --console.signing_key ${NAKAMA_CONSOLE_SIGNING_KEY}
    restart: always
    links:
      - "postgres:db"
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "${NAKAMA_CONSOLE_PORT}"
      - "${NAKAMA_HTTP_PORT}"
      - "${NAKAMA_GRPC_PORT}"
    ports:
      - "${NAKAMA_CONSOLE_HOST_PORT:-7351}:${NAKAMA_CONSOLE_PORT}"
      - "${NAKAMA_HTTP_HOST_PORT:-7350}:${NAKAMA_HTTP_PORT}"
      - "${NAKAMA_GRPC_HOST_PORT:-7349}:${NAKAMA_GRPC_PORT}"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
